id: AD1994481
base_file: f2193.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-05-31 05:11:54.229465
  last_modified_at: 2022-05-31 05:11:54.229472
